-- MySQL Script generated by MySQL Workbench
-- Wed May 30 14:40:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema saveotron_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `saveotron_db` ;

-- -----------------------------------------------------
-- Schema saveotron_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `saveotron_db` DEFAULT CHARACTER SET latin1 ;
USE `saveotron_db` ;

-- -----------------------------------------------------
-- Table `saveotron_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `saveotron_db`.`users` ;

CREATE TABLE IF NOT EXISTS `saveotron_db`.`users` (
  `username` VARCHAR(50) NOT NULL,
  `password` CHAR(68) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `saveotron_db`.`authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `saveotron_db`.`authorities` ;

CREATE TABLE IF NOT EXISTS `saveotron_db`.`authorities` (
  `username` VARCHAR(50) NOT NULL,
  `authority` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `authorities_idx_1` (`username` ASC, `authority` ASC),
  CONSTRAINT `authorities_ibfk_1`
    FOREIGN KEY (`username`)
    REFERENCES `saveotron_db`.`users` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `saveotron_db`.`code_snippets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `saveotron_db`.`code_snippets` ;

CREATE TABLE IF NOT EXISTS `saveotron_db`.`code_snippets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `text_field` LONGTEXT NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `username_idx` (`username` ASC),
  CONSTRAINT `username`
    FOREIGN KEY (`username`)
    REFERENCES `saveotron_db`.`authorities` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
